### ISSUE TITLE
Make an option in for -fixMisencodedQuals in arcad_hts_6_bamRealignerRecalibrate.pl

### ISSUE THREAD

**Issue by nrode** [SouthGreenPlatform/arcad-hts#13]
It seems that by default, the script assumes that there is a quality mispecification and use the flag -fixMisencodedQuals when calling GATK -T RealignerTargetCreator, which produces the following error message:
MESSAGE: Bad input: while fixing mis-encoded base qualities we encountered a read that was correctly encoded; we cannot handle such a mixture of reads so unfortunately the BAM must be fixed with some other tool
Would it be possible to make it an optional argument?

**Comment by gsarah** [comment]
Done.

I added a -fixMisencodedQuals in arcad_hts_6_bamRealignerRecalibrate.pl
