### ISSUE TITLE
bug in arcad_hts_4_Mapping_Arcad.pl

### ISSUE THREAD

**Issue by timflutre** [SouthGreenPlatform/arcad-hts#14]
Here is my cmd-line:

    arcad_hts_4_Mapping_Arcad.pl -i config.txt -o gbs.bam -r /data/chroms -q bioinfo.q -mapper bwa_mem

And here is what it returns:

    Argument "exitval" isn't numeric in subtraction (-) at /usr/local/bioinfo/bin/arcad_hts_4_Mapping_Arcad.pl line 124.
    Argument "Cannot find the reference file reference and/or config f..." isn't numeric in subtraction (-) at /usr/local/bioinfo/bin/arcad_hts_4_Mapping_Arcad.pl line 124.
    Odd number of elements in anonymous hash at /usr/local/bioinfo/bin/arcad_hts_4_Mapping_Arcad.pl line 124.

In `/data`, there are all files, such as `chroms.ann`, `chroms.bwt`, etc.

My env:

    $ perl -v
    This is perl, v5.8.8 built for x86_64-linux-thread-multi

**Comment by gsarah** [comment]
Should be solved. There was a bug in the error message construction
Anyway I  think your refrence path is not correct as /data/chrom will look for an absolute path.
